/*  THIS FILE WAS GENERATED BY THE TUXERA RELIANCE EDGE CONFIGURATION UTILITY.
    DO NOT MODIFY.

    Generated by configuration utility version 2.5
*/
/** @file
*/
#ifndef REDCONF_H
#define REDCONF_H

#include <string.h>

#include "ms_edgefs_cfg.h"

#endif
