/*  THIS FILE WAS GENERATED BY THE TUXERA RELIANCE EDGE CONFIGURATION UTILITY.
    DO NOT MODIFY.

    Generated by configuration utility version 2.5
*/
/** @file
*/
#include <redconf.h>
#include <redtypes.h>
#include <redmacs.h>
#include <redvolume.h>

#include "ms_edgefs_cfg.h"

/*
 * @brief This volume configuration will be init at fisrt mount.
 */
VOLCONF gaRedVolConf[REDCONF_VOLUME_COUNT] =
{
    { 0U, 0U, 0U, false, 10000U, 0U, "/sd0" },
#if REDCONF_VOLUME_COUNT > 1
    { 0U, 0U, 0U, false, 10000U, 0U, "/sd1" },
#endif
#if REDCONF_VOLUME_COUNT > 2
    { 0U, 0U, 0U, false, 10000U, 0U, "/sd2" },
#endif
#if REDCONF_VOLUME_COUNT > 3
    { 0U, 0U, 0U, false, 10000U, 0U, "/sd3" },
#endif
#if REDCONF_VOLUME_COUNT > 4
    { 0U, 0U, 0U, false, 10000U, 0U, "/sd4" },
#endif
#if REDCONF_VOLUME_COUNT > 5
    { 0U, 0U, 0U, false, 10000U, 0U, "/sd5" },
#endif
#if REDCONF_VOLUME_COUNT > 6
    { 0U, 0U, 0U, false, 10000U, 0U, "/sd6" },
#endif
#if REDCONF_VOLUME_COUNT > 7
#error "Add volume configure!"
#endif
};

